# Generated by Django 3.0.2 on 2021-08-23 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('England', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='nick',
            new_name='message',
        ),
    ]
